{
 "title": "RTSP SimpleServer Copy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Streams",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "paths{state=\"ready\"}"
    }
   ]
  },
  {
   "title": "Viewers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rtmp_conns{state=\"read\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rtmp_conns{state=\"idle\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "rtmp_conns{state=\"read\"}",
     "legendFormat": "Reading"
    },
    {
     "expr": "rtmp_conns{state=\"publish\"}",
     "legendFormat": "Publishing"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rtsp_sessions{state=\"idle\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "rtsp_sessions{state=\"read\"}",
     "legendFormat": "Reading"
    },
    {
     "expr": "rtsp_sessions{state=\"publish\"}",
     "legendFormat": "Publishing"
    },
    {}
   ]
  },
  {
   "title": "Paths",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "paths{state=\"ready\"}",
     "legendFormat": "Ready"
    },
    {
     "expr": "paths{state=\"notReady\"}",
     "legendFormat": "NotReady"
    }
   ]
  }
 ]
}